apiVersion: v1
kind: Service
metadata:
  name: lakers-club-service
spec:
  type: NodePort
  selector:
    app: lakers-club-deployment # Label selector to match the deployment
  ports:
    - protocol: TCP
      port: 80          # Port exposed to external world
      targetPort: 3000  # Port inside the container
